/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for Context.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_Concentrated_Load 503
#define IDH_Uniform_Load 504
#define IDH_Dynamic_Load_Allowance 513
#define IDH_Pedestrian_Live_Load 514
#define IDH_Load_Factors 515
#define IDH_Edit_Support 519
#define IDH_Deck_Types 521
#define IDH_Beam_Girder_Description_Steel_Beam 522
#define IDH_Beam_Girder_Description_Concrete_Beam 523
#define IDH_Wood_Beam_Girder_Description 524
#define IDH_Supporting_Components 526
#define IDH_Concrete_Slab_Deck_Type 527
#define IDH_Steel_Grid_Deck_Description 528
#define IDH_Wood_Deck_Description 529
#define IDH_Skew_Corrections 530
#define IDH_Properties_and_Distribution_Factors 531
#define IDH_Properties 532
#define IDH_Boundary_Conditions 533
#define IDH_Hinges 534
#define IDH_Limit_State_Factors 535
#define IDH_Insertion_Point 536
#define IDH_DC_Loads 537
#define IDH_DW_Loads 538
#define IDH_Design_Tandem 539
#define IDH_Design_Truck 540
#define IDH_Dual_Truck_Train 541
#define IDH_Dual_Tandem_Train 542
#define IDH_Fatigue_Truck 543
#define IDH_General_Properties_Bridge_Contractor 544
#define IDH_Bridge_Geometry_Bridge_Contractor 545
#define IDH_Cross_Section_Descriptions_Bridge_Contractor 546
#define IDH_Interior_Support_Description_Bridge_Contractor 547
#define IDH_Analysis_Parameters 548
#define IDH_Decorations 549
#define IDH_Screen_Plot_Style 550
#define IDH_Printer_Plot_Style 551
#define IDH_Select_Loadings 552
#define IDH_Select_Loadings_for_a_Table 553
#define IDH_Units_dialog_box 554
#define IDH_Paste_Special_dialog_box 555
